### ISSUE TITLE
嵌套了viewpager和fragment，没有回调监听不生效

### ISSUE THREAD

**Issue by tpnet** [1993hzw/OverScroll#1]
我的activity里面包含了fragment，在fragment里面添加OverScrollScrollView，监听，发现没有回调？？？

![image](https://user-images.githubusercontent.com/17380722/57954101-8e9dca80-7924-11e9-98b8-72352267d34f.png)
![image](https://user-images.githubusercontent.com/17380722/57954124-a5442180-7924-11e9-814d-3d9cbc43ce31.png)
![image](https://user-images.githubusercontent.com/17380722/57954172-c73da400-7924-11e9-9eb2-b8d008756782.png)

**Comment by 1993hzw** [comment]
请参考文档里面的使用，OverScrollView的根布局必须是CoordinatorLayout。
